#!/bin/bash

# OS specific commands
case "$(uname -s)" in
  Darwin)
    echo "hello from iOS"

    # command line colors and colors for 'ls' command
    #export CLICOLOR=1
    #export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
    ;;
  Linux)
    echo "hello from Linux"
    ;;
esac

# source unversioned settings
if [ -r ~/.bash_unversioned ]; then
  source ~/.bash_unversioned
fi

# aliases - general
alias brl='. ~/.bash_common' # reload .bash_common
alias ll='ls -alF'

# aliases - git
alias b="git branch -l"
alias br="git branch -lr"
alias d="git diff"
alias ds="git diff --staged"
alias gcm="git checkout master"
alias l="git log --decorate=short"
alias s="git status"
