# bundler
alias be="bundle exec"
alias bi="bundle install"

# git
alias d="git diff"
alias ds="git diff --staged"
alias gitppr="git pull --rebase && git push"
alias gitsu="git submodule sync; git pull --recurse-submodules; git submodule update --init --recursive"
alias s="git status"

# postgres
alias pg="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log"

# rails
alias db="be rails db"
alias rc="be rails c"
alias rdbm="be rake db:migrate"
alias rs="be rails s"

# system
alias ll="ls -lF"

###################################################
# environment variables (these should go elsewhere)
GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT
