colorscheme desert   " color scheme
set gfn=Monaco:h18   " set gui font to Monaco, size 18
set number           " enable line numbers
set ruler            " enable ruler (cursor row/column)
syntax on            " enable syntax highlighting
