colorscheme desert   " color scheme
set number           " enable line numbers
set ruler            " enable ruler (cursor row/column)
set expandtab        " change tab to spaces
set tabstop=2        " tab stop of 2 spaces
syntax on            " enable syntax highlighting

" from http://stackoverflow.com/questions/774560
" Uncomment the following to have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
